//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CertSYS
{
    using System;
    using System.Collections.Generic;
    
    public partial class produto
    {
        public int pro_cod { get; set; }
        public string pro_nome { get; set; }
        public Nullable<double> pro_qtde { get; set; }
        public int for_cod { get; set; }
    
        public virtual fornecedor fornecedor { get; set; }
    }
}
