//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CertSYS
{
    using System;
    using System.Collections.Generic;
    
    public partial class usuario
    {
        public int usu_cod { get; set; }
        public string usu_nome { get; set; }
        public string usu_login { get; set; }
        public string usu_senha { get; set; }
    }
}
